name: Bug Report
description: File a bug report.
title: 'Bug: '
labels: ['bug']
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info ?
      placeholder: email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened ?
      description: Please provide a detailed description of the issue.
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on ?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Internet Explorer
        - Samsung Internet
        - Other mobile browser
        - Other desktop browser
  - type: dropdown
    id: systems
    attributes:
      label: What systems are you seeing the problem on ?
      multiple: true
      options:
        - Windows
        - macOS
        - Linux
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/MaximePremont/boilerplate-nextron-shadcn/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
